# Generated by Django 6.0.3 on 2026-03-12 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobre', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('inicio_manha', models.TimeField(blank=True, null=True)),
                ('fim_manha', models.TimeField(blank=True, null=True)),
                ('inicio_tarde', models.TimeField(blank=True, null=True)),
                ('fim_tarde', models.TimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duracao_minutos', models.PositiveIntegerField(choices=[(15, '15 min'), (30, '30 min'), (60, '60 min')], default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('codigo_redf', models.IntegerField(default=0)),
                ('e_barbeiro', models.BooleanField(default=False)),
                ('nome_barbeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.barbeiros')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(default='', max_length=10000)),
                ('data', models.DateTimeField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.barbeiros')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usuarios')),
            ],
        ),
    ]
