# Generated by Django 6.0.3 on 2026-03-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiros',
            name='sobre',
        ),
    ]
